# Generated by Django 5.0.3 on 2024-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='host',
            field=models.CharField(default='abc', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
